### ISSUE TITLE
Browser chess championship

### ISSUE THREAD

**Issue by vprelovac** [Strryke/betafish#2]
Fantastic work!

An idea popped up while testing it. How about organizing browser chess chanmpionship. Instead of chess engines, it is browsers competing with the same chess engine (betafish). The reason it would work is mainstream browsers (Chrome/Firefox/Safari) have different implementations of javascript engine which would produce a difference in performance with a fixed time allotment (say 1s). 

That way we could get Browser Elo!

**Comment by Strryke** [comment]
Interesting idea. I just did some rudimentary tests on Safari, Chrome, Brave & Firefox and they all reached a depth of 6 given 1s of thinking time. I think, given how the time taken to reach a new depth increases quite exponentially (branching factor of ~20-30), the performance difference will have to be quite immense for a JS runtime to reach a new depth, so it's unlikely that testing this way will provide a good benchmark.
