### ISSUE TITLE
How do I use this library?

### ISSUE THREAD

**Issue by Hugos68** [Strryke/betafish#3]
``npm i betafish`` doesn't work, how can i use it in my project

**Comment by urobot2011** [comment]
This not library. But you have https://github.com/maksimKorzh/wukongJS 👍

**Comment by Strryke** [comment]
Hey Hugo,

This isn't a library, its a personal project that I made. It's not meant to be used as a library, but you can look through the source code and copy whatever you need as long as you credit it properly.

If you want to use the engine, you can take a look at `betafish.js` and see the functions that I expose at the bottom, and see how they can be used together with a GUI library to get your game working. If you need more help, please provide me with more details on how you plan to use it and I'll see how I can help.
